# Generated by Django 5.0 on 2023-12-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_masterform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterForm',
        ),
    ]
